# Check on http://lint.travis-ci.org/ after modifying!
language: python
python:
  - "2.7"
before_install:
  - wget http://repo.continuum.io/miniconda/Miniconda3-3.7.3-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=/home/travis/miniconda3/bin:$PATH
  - sudo apt-get -qq update
  - sudo apt-get -qq install r-base
  - wget http://cran.r-project.org/src/contrib/gee_4.13-19.tar.gz -O gee.tar.gz
  - wget http://cran.r-project.org/src/contrib/Archive/ape/ape_3.0.tar.gz -O ape.tar.gz
  - sudo R CMD INSTALL gee.tar.gz
  - sudo R CMD INSTALL ape.tar.gz
install:
  - conda create --yes -n env_name python=$TRAVIS_PYTHON_VERSION pip numpy scipy 
  - conda install --yes -n env_name cython
  - conda install --yes -n env_name h5py>=2.2.0
  - source activate env_name
  - pip install cogent biom-format
  - pip install -e . --no-deps
script:
  - python tests/all_tests.py
