name: PICRUSt
version: 1
summary: PICRUSt: Phylogenetic Investigation of Communities by Reconstruction of Unobserved States
description: PICRUSt (pronounced “pie crust”) is a bioinformatics software package designed to predict metagenome functional content from marker gene (e.g., 16S rRNA) surveys and full genomes. PICRUSt is freely available under the GPL.

